package com.juliorodriguez.transcron.vista;

import com.juliorodriguez.transcron.modelo.Empresa;
import com.juliorodriguez.transcron.modelo.Vehiculo;

import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Vista extends javax.swing.JPanel {
    private DefaultTableModel modelo;
    private Vector data;

    public Vista() {
        initComponents();
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public JButton getBtnActualizar() {
        return btnActualizar;
    }

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnEmpresa() {
        return btnEmpresa;
    }

    public JScrollPane getScrollPane() {
        return scrollPane;
    }

    public Vector getData() {
        return data;
    }

    public void setData(Vector data) {
        this.data = data;
    }

    public JTable getTableEmpresa() {
        return tableEmpresa;
    }

    public JTable getTableVehiculo() {
        return tableVehiculo;
    }

    public void cargarTablaEmpresas() {
        modelo = (DefaultTableModel) this.tableEmpresa.getModel();
        modelo.setRowCount(0);
        //modelo.addRow(data);

        for (int i = 0; i < data.size(); i++) {
            //modelo.addRow((Object[]) data.get(i));
            Empresa row = (Empresa) data.get(i);
            modelo.addRow(new Object[]{row.getId(),  row.getNo_documento(),  row.getTipo(),  row.getNombre(),
                    row.getDireccion(),  row.getCiudad(),  row.getDepartamento(),  row.getPais(),  row.getTelefono()});
        }
    }

    public void cargarTablaVehiculo() {
        modelo = (DefaultTableModel) this.tableVehiculo.getModel();
        modelo.setRowCount(0);
        //modelo.addRow(data);

        for (int i = 0; i < data.size(); i++) {
            //modelo.addRow((Object[]) data.get(i));
            Vehiculo row = (Vehiculo) data.get(i);
            modelo.addRow(new Object[]{row.getId(),  row.getPlaca(),  row.getEmpresa(),  row.getTipo_doc_empresa(),
                    row.getNo_doc_empresa(),  row.getRepresentante_legal(),  row.getTipo_doc_representante(),
                    row.getNo_doc_representante(),  row.getNo_conductores()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tableEmpresa = new javax.swing.JTable();
        tableVehiculo = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 400));

        scrollPane.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tableEmpresa.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "id", "no_documento", "tipo", "nombre", "direccion", "ciudad","departamento","pais","telefono"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        tableVehiculo.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "id", "placa", "empresa", "tipo_doc_empresa", "no_doc_empresa", "representante_legal",
                        "tipo_doc_representante","no_doc_representante","numero_de_conductores"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        scrollPane.setViewportView(tableEmpresa);
        scrollPane.setViewportView(tableVehiculo);

        btnCrear.setText("Crear");

        btnActualizar.setText("Actualizar");

        btnEliminar.setText("Eliminar");

        btnEmpresa.setText("Ver Empresas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnCrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizar)
                                .addGap(127, 127, 127)
                                .addComponent(btnEliminar)
                                .addGap(84, 84, 84)
                                .addComponent(btnEmpresa)
                                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCrear)
                                        .addComponent(btnActualizar)
                                        .addComponent(btnEliminar)
                                        .addComponent(btnEmpresa))
                                .addGap(18, 18, 18)
                                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tableEmpresa;
    private javax.swing.JTable tableVehiculo;
    // End of variables declaration
}

